## port par défaut 5432
# Utilise l'image postgres
FROM mcr.microsoft.com/mssql/server:2019-latest

ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD=1234
ENV MSSQL_PID=22222-00000-00000-00000-00000

VOLUME [ "/data" ]