## port par défaut 8081
# Utilise l'image postgres
FROM mongo:8.0.13

ENV MONGO_INITDB_ROOT_USERNAME: root
ENV MONGO_INITDB_ROOT_PASSWORD: 1234

# Créer une base de donnée nommée mydatabase
ENV MONGO_INITDB_DATABASE=mydatabase
